name: Deploy to Google Cloud Run

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'backend/**'



jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v3'
      with:
        workload_identity_provider: 'projects/515687049194/locations/global/workloadIdentityPools/gh-actions/providers/github-provider'
        service_account: 'github-deployer@gen-lang-client-0584302719.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v3'
      with:
        service: 'removebgbackend'
        image: 'docker.io/kaustavs/removebgbackend:latest'

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
