name: gcp_psh

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        uses: 'google-github-actions/auth@v3'
        with:
            workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
            service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - 
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
            service: 'removebgbackend'
            image: 'docker.io/kaustavs/removebgbackend:latest'

      -
        name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'