name: push_backend

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: kaustavs/removebgbackend:latest
  deploy_to_gcp:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: 'projects/515687049194/locations/global/workloadIdentityPools/gh-actions/providers/github-provider'
        service_account: 'github-deployer@gen-lang-client-0584302719.iam.gserviceaccount.com'

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: 'gen-lang-client-0584302719'

    - name: Pull image from Docker Hub
      run: docker pull docker.io/kaustavs/removebgbackend:latest

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Tag and push image to Artifact Registry
      run: |
        docker tag docker.io/kaustavs/removebgbackend:latest asia-south1-docker.pkg.dev/gen-lang-client-0584302719/removebgbackend/removebgbackend:latest
        docker push asia-south1-docker.pkg.dev/gen-lang-client-0584302719/removebgbackend/removebgbackend:latest

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v3
      with:
        service: 'removebgbackend'
        image: 'asia-south1-docker.pkg.dev/gen-lang-client-0584302719/removebgbackend/removebgbackend:latest'
        region: 'asia-south1'
        memory: '1Gi'

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
